[mypy]
python_version = 3.10
ignore_missing_imports = True
check_untyped_defs = False

[mypy-whisper.*]
ignore_missing_imports = True

[mypy-spacy.*]
ignore_missing_imports = True

[mypy-pyannote.*]
ignore_missing_imports = True

[mypy-torch.*]
ignore_missing_imports = True

[mypy-sounddevice.*]
ignore_missing_imports = True

[mypy-soundfile.*]
ignore_missing_imports = True

[mypy-pydub.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-reportlab.*]
ignore_missing_imports = True

[mypy-docx.*]
ignore_missing_imports = True

[mypy-nltk.*]
ignore_missing_imports = True

[mypy-cryptography.*]
ignore_missing_imports = True
